//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 02:01:18 PM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for afatipusTipus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="afatipusTipus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TAM"/&gt;
 *     &lt;enumeration value="AAM"/&gt;
 *     &lt;enumeration value="EU"/&gt;
 *     &lt;enumeration value="EUK"/&gt;
 *     &lt;enumeration value="MAA"/&gt;
 *     &lt;enumeration value="F.AFA"/&gt;
 *     &lt;enumeration value="K.AFA"/&gt;
 *     &lt;enumeration value="ÁKK"/&gt;
 *     &lt;enumeration value="TAHK"/&gt;
 *     &lt;enumeration value="TEHK"/&gt;
 *     &lt;enumeration value="EUT"/&gt;
 *     &lt;enumeration value="EUKT"/&gt;
 *     &lt;enumeration value="HO"/&gt;
 *     &lt;enumeration value="EUE"/&gt;
 *     &lt;enumeration value="EUFADE"/&gt;
 *     &lt;enumeration value="EUFAD37"/&gt;
 *     &lt;enumeration value="ATK"/&gt;
 *     &lt;enumeration value="NAM"/&gt;
 *     &lt;enumeration value="EAM"/&gt;
 *     &lt;enumeration value="KBAUK"/&gt;
 *     &lt;enumeration value="KBAET"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "afatipusTipus")
@XmlEnum
public enum AfatipusTipus {

    TAM("TAM"),
    AAM("AAM"),
    EU("EU"),
    EUK("EUK"),
    MAA("MAA"),
    @XmlEnumValue("F.AFA")
    F_AFA("F.AFA"),
    @XmlEnumValue("K.AFA")
    K_AFA("K.AFA"),
    ÁKK("\u00c1KK"),
    TAHK("TAHK"),
    TEHK("TEHK"),
    EUT("EUT"),
    EUKT("EUKT"),
    HO("HO"),
    EUE("EUE"),
    EUFADE("EUFADE"),
    @XmlEnumValue("EUFAD37")
    EUFAD_37("EUFAD37"),
    ATK("ATK"),
    NAM("NAM"),
    EAM("EAM"),
    KBAUK("KBAUK"),
    KBAET("KBAET");
    private final String value;

    AfatipusTipus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AfatipusTipus fromValue(String v) {
        for (AfatipusTipus c: AfatipusTipus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
