//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 11:04:20 PM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for alapTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alapTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="hivasAzonosito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nyugtaszam" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipus" type="{http://www.szamlazz.hu/xmlnyugtavalasz}nyugtatipusTipus"/&gt;
 *         &lt;element name="stornozott" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="stornozottNyugtaszam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kelt" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="fizmod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="penznem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="devizabank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="devizaarf" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="megjegyzes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fokonyvVevo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="teszt" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alapTipus", propOrder = {

})
public class AlapTipus {

    protected int id;
    protected String hivasAzonosito;
    @XmlElement(required = true)
    protected String nyugtaszam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NyugtatipusTipus tipus;
    protected boolean stornozott;
    protected String stornozottNyugtaszam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar kelt;
    @XmlElement(required = true)
    protected String fizmod;
    @XmlElement(required = true)
    protected String penznem;
    protected String devizabank;
    protected Double devizaarf;
    protected String megjegyzes;
    protected String fokonyvVevo;
    protected boolean teszt;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the hivasAzonosito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHivasAzonosito() {
        return hivasAzonosito;
    }

    /**
     * Sets the value of the hivasAzonosito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHivasAzonosito(String value) {
        this.hivasAzonosito = value;
    }

    /**
     * Gets the value of the nyugtaszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNyugtaszam() {
        return nyugtaszam;
    }

    /**
     * Sets the value of the nyugtaszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNyugtaszam(String value) {
        this.nyugtaszam = value;
    }

    /**
     * Gets the value of the tipus property.
     * 
     * @return
     *     possible object is
     *     {@link NyugtatipusTipus }
     *     
     */
    public NyugtatipusTipus getTipus() {
        return tipus;
    }

    /**
     * Sets the value of the tipus property.
     * 
     * @param value
     *     allowed object is
     *     {@link NyugtatipusTipus }
     *     
     */
    public void setTipus(NyugtatipusTipus value) {
        this.tipus = value;
    }

    /**
     * Gets the value of the stornozott property.
     * 
     */
    public boolean isStornozott() {
        return stornozott;
    }

    /**
     * Sets the value of the stornozott property.
     * 
     */
    public void setStornozott(boolean value) {
        this.stornozott = value;
    }

    /**
     * Gets the value of the stornozottNyugtaszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStornozottNyugtaszam() {
        return stornozottNyugtaszam;
    }

    /**
     * Sets the value of the stornozottNyugtaszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStornozottNyugtaszam(String value) {
        this.stornozottNyugtaszam = value;
    }

    /**
     * Gets the value of the kelt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKelt() {
        return kelt;
    }

    /**
     * Sets the value of the kelt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKelt(XMLGregorianCalendar value) {
        this.kelt = value;
    }

    /**
     * Gets the value of the fizmod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFizmod() {
        return fizmod;
    }

    /**
     * Sets the value of the fizmod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFizmod(String value) {
        this.fizmod = value;
    }

    /**
     * Gets the value of the penznem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenznem() {
        return penznem;
    }

    /**
     * Sets the value of the penznem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenznem(String value) {
        this.penznem = value;
    }

    /**
     * Gets the value of the devizabank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevizabank() {
        return devizabank;
    }

    /**
     * Sets the value of the devizabank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevizabank(String value) {
        this.devizabank = value;
    }

    /**
     * Gets the value of the devizaarf property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDevizaarf() {
        return devizaarf;
    }

    /**
     * Sets the value of the devizaarf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDevizaarf(Double value) {
        this.devizaarf = value;
    }

    /**
     * Gets the value of the megjegyzes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegjegyzes() {
        return megjegyzes;
    }

    /**
     * Sets the value of the megjegyzes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegjegyzes(String value) {
        this.megjegyzes = value;
    }

    /**
     * Gets the value of the fokonyvVevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFokonyvVevo() {
        return fokonyvVevo;
    }

    /**
     * Sets the value of the fokonyvVevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFokonyvVevo(String value) {
        this.fokonyvVevo = value;
    }

    /**
     * Gets the value of the teszt property.
     * 
     */
    public boolean isTeszt() {
        return teszt;
    }

    /**
     * Sets the value of the teszt property.
     * 
     */
    public void setTeszt(boolean value) {
        this.teszt = value;
    }

}
