//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 11:25:36 AM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fokonyvtetelTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fokonyvtetelTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="arbevetel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="afa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fokonyvtetelTipus", propOrder = {

})
public class FokonyvtetelTipus {

    protected String arbevetel;
    protected String afa;

    /**
     * Gets the value of the arbevetel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArbevetel() {
        return arbevetel;
    }

    /**
     * Sets the value of the arbevetel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArbevetel(String value) {
        this.arbevetel = value;
    }

    /**
     * Gets the value of the afa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfa() {
        return afa;
    }

    /**
     * Sets the value of the afa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfa(String value) {
        this.afa = value;
    }

}
