//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 11:25:36 AM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nyugtaTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nyugtaTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="alap" type="{http://www.szamlazz.hu/xmlnyugtavalasz}alapTipus"/&gt;
 *         &lt;element name="tetelek" type="{http://www.szamlazz.hu/xmlnyugtavalasz}tetelekTipus"/&gt;
 *         &lt;element name="kifizetesek" type="{http://www.szamlazz.hu/xmlnyugtavalasz}kifizetesekTipus" minOccurs="0"/&gt;
 *         &lt;element name="osszegek" type="{http://www.szamlazz.hu/xmlnyugtavalasz}osszegekTipus"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nyugtaTipus", propOrder = {

})
public class NyugtaTipus {

    @XmlElement(required = true)
    protected AlapTipus alap;
    @XmlElement(required = true)
    protected TetelekTipus tetelek;
    protected KifizetesekTipus kifizetesek;
    @XmlElement(required = true)
    protected OsszegekTipus osszegek;

    /**
     * Gets the value of the alap property.
     * 
     * @return
     *     possible object is
     *     {@link AlapTipus }
     *     
     */
    public AlapTipus getAlap() {
        return alap;
    }

    /**
     * Sets the value of the alap property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlapTipus }
     *     
     */
    public void setAlap(AlapTipus value) {
        this.alap = value;
    }

    /**
     * Gets the value of the tetelek property.
     * 
     * @return
     *     possible object is
     *     {@link TetelekTipus }
     *     
     */
    public TetelekTipus getTetelek() {
        return tetelek;
    }

    /**
     * Sets the value of the tetelek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TetelekTipus }
     *     
     */
    public void setTetelek(TetelekTipus value) {
        this.tetelek = value;
    }

    /**
     * Gets the value of the kifizetesek property.
     * 
     * @return
     *     possible object is
     *     {@link KifizetesekTipus }
     *     
     */
    public KifizetesekTipus getKifizetesek() {
        return kifizetesek;
    }

    /**
     * Sets the value of the kifizetesek property.
     * 
     * @param value
     *     allowed object is
     *     {@link KifizetesekTipus }
     *     
     */
    public void setKifizetesek(KifizetesekTipus value) {
        this.kifizetesek = value;
    }

    /**
     * Gets the value of the osszegek property.
     * 
     * @return
     *     possible object is
     *     {@link OsszegekTipus }
     *     
     */
    public OsszegekTipus getOsszegek() {
        return osszegek;
    }

    /**
     * Sets the value of the osszegek property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsszegekTipus }
     *     
     */
    public void setOsszegek(OsszegekTipus value) {
        this.osszegek = value;
    }

}
