//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 08:51:13 AM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.szamlazz.xmlnyugtavalasz package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.szamlazz.xmlnyugtavalasz
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xmlnyugtavalasz }
     * 
     */
    public Xmlnyugtavalasz createXmlnyugtavalasz() {
        return new Xmlnyugtavalasz();
    }

    /**
     * Create an instance of {@link NyugtaTipus }
     * 
     */
    public NyugtaTipus createNyugtaTipus() {
        return new NyugtaTipus();
    }

    /**
     * Create an instance of {@link AlapTipus }
     * 
     */
    public AlapTipus createAlapTipus() {
        return new AlapTipus();
    }

    /**
     * Create an instance of {@link FokonyvtetelTipus }
     * 
     */
    public FokonyvtetelTipus createFokonyvtetelTipus() {
        return new FokonyvtetelTipus();
    }

    /**
     * Create an instance of {@link TetelTipus }
     * 
     */
    public TetelTipus createTetelTipus() {
        return new TetelTipus();
    }

    /**
     * Create an instance of {@link TetelekTipus }
     * 
     */
    public TetelekTipus createTetelekTipus() {
        return new TetelekTipus();
    }

    /**
     * Create an instance of {@link AfakulcsosszTipus }
     * 
     */
    public AfakulcsosszTipus createAfakulcsosszTipus() {
        return new AfakulcsosszTipus();
    }

    /**
     * Create an instance of {@link TotalosszTipus }
     * 
     */
    public TotalosszTipus createTotalosszTipus() {
        return new TotalosszTipus();
    }

    /**
     * Create an instance of {@link OsszegekTipus }
     * 
     */
    public OsszegekTipus createOsszegekTipus() {
        return new OsszegekTipus();
    }

    /**
     * Create an instance of {@link KifizetesTipus }
     * 
     */
    public KifizetesTipus createKifizetesTipus() {
        return new KifizetesTipus();
    }

    /**
     * Create an instance of {@link KifizetesekTipus }
     * 
     */
    public KifizetesekTipus createKifizetesekTipus() {
        return new KifizetesekTipus();
    }

}
