//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 11:25:36 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.szamlazz.hu/xmlnyugtavalasz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.szamlazz.xmlnyugtavalasz;
