//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 08:51:13 AM CEST 
//


package hu.szamlazz.xmlnyugtavalasz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for totalosszTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="totalosszTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="netto" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="afa" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="brutto" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "totalosszTipus", propOrder = {

})
public class TotalosszTipus {

    protected double netto;
    protected double afa;
    protected double brutto;

    /**
     * Gets the value of the netto property.
     * 
     */
    public double getNetto() {
        return netto;
    }

    /**
     * Sets the value of the netto property.
     * 
     */
    public void setNetto(double value) {
        this.netto = value;
    }

    /**
     * Gets the value of the afa property.
     * 
     */
    public double getAfa() {
        return afa;
    }

    /**
     * Sets the value of the afa property.
     * 
     */
    public void setAfa(double value) {
        this.afa = value;
    }

    /**
     * Gets the value of the brutto property.
     * 
     */
    public double getBrutto() {
        return brutto;
    }

    /**
     * Sets the value of the brutto property.
     * 
     */
    public void setBrutto(double value) {
        this.brutto = value;
    }

}
