version: '3'

services:
  app:
    build: .
    container_name: invoiceagent_app
    ports:
     - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 5s
