//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 02:01:18 PM CEST 
//


package hu.szamlazz.xmlnyugtasend;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emailKuldes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emailKuldes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emailReplyto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emailTargy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emailSzoveg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailKuldes", propOrder = {
    "email",
    "emailReplyto",
    "emailTargy",
    "emailSzoveg"
})
public class EmailKuldes {

    protected String email;
    protected String emailReplyto;
    protected String emailTargy;
    protected String emailSzoveg;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the emailReplyto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailReplyto() {
        return emailReplyto;
    }

    /**
     * Sets the value of the emailReplyto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailReplyto(String value) {
        this.emailReplyto = value;
    }

    /**
     * Gets the value of the emailTargy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailTargy() {
        return emailTargy;
    }

    /**
     * Sets the value of the emailTargy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailTargy(String value) {
        this.emailTargy = value;
    }

    /**
     * Gets the value of the emailSzoveg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSzoveg() {
        return emailSzoveg;
    }

    /**
     * Sets the value of the emailSzoveg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSzoveg(String value) {
        this.emailSzoveg = value;
    }

}
