//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 02:01:18 PM CEST 
//


package hu.szamlazz.xmlnyugtasend;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fejlecTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fejlecTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nyugtaszam" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fejlecTipus", propOrder = {
    "nyugtaszam"
})
public class FejlecTipus {

    @XmlElement(required = true)
    protected String nyugtaszam;

    /**
     * Gets the value of the nyugtaszam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNyugtaszam() {
        return nyugtaszam;
    }

    /**
     * Sets the value of the nyugtaszam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNyugtaszam(String value) {
        this.nyugtaszam = value;
    }

}
