//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 02:01:18 PM CEST 
//


package hu.szamlazz.xmlnyugtacreate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fejlecTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fejlecTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="hivasAzonosito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="elotag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fizmod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="penznem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="devizaarf" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="devizabank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="megjegyzes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pdfSablon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fokonyvVevo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fejlecTipus", propOrder = {

})
public class FejlecTipus {

    protected String hivasAzonosito;
    @XmlElement(required = true)
    protected String elotag;
    @XmlElement(required = true)
    protected String fizmod;
    @XmlElement(required = true)
    protected String penznem;
    protected Double devizaarf;
    protected String devizabank;
    protected String megjegyzes;
    protected String pdfSablon;
    protected String fokonyvVevo;

    /**
     * Gets the value of the hivasAzonosito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHivasAzonosito() {
        return hivasAzonosito;
    }

    /**
     * Sets the value of the hivasAzonosito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHivasAzonosito(String value) {
        this.hivasAzonosito = value;
    }

    /**
     * Gets the value of the elotag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElotag() {
        return elotag;
    }

    /**
     * Sets the value of the elotag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElotag(String value) {
        this.elotag = value;
    }

    /**
     * Gets the value of the fizmod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFizmod() {
        return fizmod;
    }

    /**
     * Sets the value of the fizmod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFizmod(String value) {
        this.fizmod = value;
    }

    /**
     * Gets the value of the penznem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPenznem() {
        return penznem;
    }

    /**
     * Sets the value of the penznem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPenznem(String value) {
        this.penznem = value;
    }

    /**
     * Gets the value of the devizaarf property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDevizaarf() {
        return devizaarf;
    }

    /**
     * Sets the value of the devizaarf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDevizaarf(Double value) {
        this.devizaarf = value;
    }

    /**
     * Gets the value of the devizabank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevizabank() {
        return devizabank;
    }

    /**
     * Sets the value of the devizabank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevizabank(String value) {
        this.devizabank = value;
    }

    /**
     * Gets the value of the megjegyzes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegjegyzes() {
        return megjegyzes;
    }

    /**
     * Sets the value of the megjegyzes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegjegyzes(String value) {
        this.megjegyzes = value;
    }

    /**
     * Gets the value of the pdfSablon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfSablon() {
        return pdfSablon;
    }

    /**
     * Sets the value of the pdfSablon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfSablon(String value) {
        this.pdfSablon = value;
    }

    /**
     * Gets the value of the fokonyvVevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFokonyvVevo() {
        return fokonyvVevo;
    }

    /**
     * Sets the value of the fokonyvVevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFokonyvVevo(String value) {
        this.fokonyvVevo = value;
    }

}
