//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 11:04:20 PM CEST 
//


package hu.szamlazz.xmlnyugtacreate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tetelTipus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tetelTipus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="megnevezes" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="azonosito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mennyiseg" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="mennyisegiEgyseg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nettoEgysegar" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="afakulcs" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="netto" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="afa" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="brutto" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="fokonyv" type="{http://www.szamlazz.hu/xmlnyugtacreate}tetelFokonyvTipus" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tetelTipus", propOrder = {

})
public class TetelTipus {

    @XmlElement(required = true)
    protected String megnevezes;
    protected String azonosito;
    protected double mennyiseg;
    @XmlElement(required = true)
    protected String mennyisegiEgyseg;
    protected double nettoEgysegar;
    @XmlElement(required = true)
    protected String afakulcs;
    protected double netto;
    protected double afa;
    protected double brutto;
    protected TetelFokonyvTipus fokonyv;

    /**
     * Gets the value of the megnevezes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMegnevezes() {
        return megnevezes;
    }

    /**
     * Sets the value of the megnevezes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMegnevezes(String value) {
        this.megnevezes = value;
    }

    /**
     * Gets the value of the azonosito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzonosito() {
        return azonosito;
    }

    /**
     * Sets the value of the azonosito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzonosito(String value) {
        this.azonosito = value;
    }

    /**
     * Gets the value of the mennyiseg property.
     * 
     */
    public double getMennyiseg() {
        return mennyiseg;
    }

    /**
     * Sets the value of the mennyiseg property.
     * 
     */
    public void setMennyiseg(double value) {
        this.mennyiseg = value;
    }

    /**
     * Gets the value of the mennyisegiEgyseg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMennyisegiEgyseg() {
        return mennyisegiEgyseg;
    }

    /**
     * Sets the value of the mennyisegiEgyseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMennyisegiEgyseg(String value) {
        this.mennyisegiEgyseg = value;
    }

    /**
     * Gets the value of the nettoEgysegar property.
     * 
     */
    public double getNettoEgysegar() {
        return nettoEgysegar;
    }

    /**
     * Sets the value of the nettoEgysegar property.
     * 
     */
    public void setNettoEgysegar(double value) {
        this.nettoEgysegar = value;
    }

    /**
     * Gets the value of the afakulcs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfakulcs() {
        return afakulcs;
    }

    /**
     * Sets the value of the afakulcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfakulcs(String value) {
        this.afakulcs = value;
    }

    /**
     * Gets the value of the netto property.
     * 
     */
    public double getNetto() {
        return netto;
    }

    /**
     * Sets the value of the netto property.
     * 
     */
    public void setNetto(double value) {
        this.netto = value;
    }

    /**
     * Gets the value of the afa property.
     * 
     */
    public double getAfa() {
        return afa;
    }

    /**
     * Sets the value of the afa property.
     * 
     */
    public void setAfa(double value) {
        this.afa = value;
    }

    /**
     * Gets the value of the brutto property.
     * 
     */
    public double getBrutto() {
        return brutto;
    }

    /**
     * Sets the value of the brutto property.
     * 
     */
    public void setBrutto(double value) {
        this.brutto = value;
    }

    /**
     * Gets the value of the fokonyv property.
     * 
     * @return
     *     possible object is
     *     {@link TetelFokonyvTipus }
     *     
     */
    public TetelFokonyvTipus getFokonyv() {
        return fokonyv;
    }

    /**
     * Sets the value of the fokonyv property.
     * 
     * @param value
     *     allowed object is
     *     {@link TetelFokonyvTipus }
     *     
     */
    public void setFokonyv(TetelFokonyvTipus value) {
        this.fokonyv = value;
    }

}
