//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.15 at 02:01:18 PM CEST 
//


package hu.szamlazz.xmlnyugtacreate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="beallitasok" type="{http://www.szamlazz.hu/xmlnyugtacreate}beallitasokTipus"/&gt;
 *         &lt;element name="fejlec" type="{http://www.szamlazz.hu/xmlnyugtacreate}fejlecTipus"/&gt;
 *         &lt;element name="tetelek" type="{http://www.szamlazz.hu/xmlnyugtacreate}tetelekTipus"/&gt;
 *         &lt;element name="kifizetesek" type="{http://www.szamlazz.hu/xmlnyugtacreate}kifizetesekTipus" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "xmlnyugtacreate")
public class Xmlnyugtacreate {

    @XmlElement(required = true)
    protected BeallitasokTipus beallitasok;
    @XmlElement(required = true)
    protected FejlecTipus fejlec;
    @XmlElement(required = true)
    protected TetelekTipus tetelek;
    protected KifizetesekTipus kifizetesek;

    /**
     * Gets the value of the beallitasok property.
     * 
     * @return
     *     possible object is
     *     {@link BeallitasokTipus }
     *     
     */
    public BeallitasokTipus getBeallitasok() {
        return beallitasok;
    }

    /**
     * Sets the value of the beallitasok property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeallitasokTipus }
     *     
     */
    public void setBeallitasok(BeallitasokTipus value) {
        this.beallitasok = value;
    }

    /**
     * Gets the value of the fejlec property.
     * 
     * @return
     *     possible object is
     *     {@link FejlecTipus }
     *     
     */
    public FejlecTipus getFejlec() {
        return fejlec;
    }

    /**
     * Sets the value of the fejlec property.
     * 
     * @param value
     *     allowed object is
     *     {@link FejlecTipus }
     *     
     */
    public void setFejlec(FejlecTipus value) {
        this.fejlec = value;
    }

    /**
     * Gets the value of the tetelek property.
     * 
     * @return
     *     possible object is
     *     {@link TetelekTipus }
     *     
     */
    public TetelekTipus getTetelek() {
        return tetelek;
    }

    /**
     * Sets the value of the tetelek property.
     * 
     * @param value
     *     allowed object is
     *     {@link TetelekTipus }
     *     
     */
    public void setTetelek(TetelekTipus value) {
        this.tetelek = value;
    }

    /**
     * Gets the value of the kifizetesek property.
     * 
     * @return
     *     possible object is
     *     {@link KifizetesekTipus }
     *     
     */
    public KifizetesekTipus getKifizetesek() {
        return kifizetesek;
    }

    /**
     * Sets the value of the kifizetesek property.
     * 
     * @param value
     *     allowed object is
     *     {@link KifizetesekTipus }
     *     
     */
    public void setKifizetesek(KifizetesekTipus value) {
        this.kifizetesek = value;
    }

}
